version: '3'
services:
  jenkins:
    image: mrinternauta/jenkins-cli
    container_name: jenkins-ci
    privileged: true
    user: root
    ports:
      - 7001:8080
      - 50000:50000
    volumes:
    #mount docker socket to jenkins execute docker
      - ./jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
